#!/bin/bash

# OpenZxicEditor
# 版权所有 (C) 2024 ufiTech & OpenZxicEditor Developers.

# 本程序是自由软件：您可以基于自由软件基金会发布的GNU Affero通用公共许可证的条款下重新分发和/或修改它，或者本许可证第三版或者（由您选择）任何后续版本。
# 分发本程序是希望它能派上用场，但没有任何担保，甚至也没有对其适销性或特定目的适用性的默示担保。更多细节请参见“GNU Affero通用公共许可证”。
# 您应该已收到本程序随附的GNU Affero通用公共许可证的副本。如未收到，请参见：http://www.gnu.org/licenses/ 。

# 获取脚本所在路径
get_script_dir() {
    local script_path="$0"
    if [ "${script_path:0:1}" != "/" ]; then
        script_path="$(command -v readlink >/dev/null 2>&1 && { readlink -f "$script_path" || :; } || { realpath "$script_path" || :; } || echo "$PWD/$script_path")"
    fi
    local script_dir="$(dirname "$script_path")"
    echo "$script_dir"
}

# 设置工作目录为所在目录
cd "$(get_script_dir)"

# 接收命令行参数
file="$1"

# 检查文件是否存在
if [ ! -f "$file" ]; then
    # 没有找到文件，将会提示用户如何使用
    echo "用途：从完整编程器固件中分拆出各分区并创建工程文件夹"
    echo "用法：将源文件路径作为第一个参数传入"
else
    # 分割传入的文件
    lua __lib__/mtdcut-nonfree.luac "$file"
    echo ""
    # echo "分拆完成，请使用 unpack-mtd 工具进一步解包各分区"
    . ./unpack-mtd
fi
