#!/bin/bash

# 设置工作目录为当前所在目录
cd "$(dirname "\$0")"

# 接收路径
file="\$1"

# 合并所有MTD为全镜像
if [ -e "$file" ]; then
    # 使用拖拽路径
    lua __lib__/mtdjoin.lua "$file"
elif [ -d "MTDs" ]; then
    # 使用经典路径
    lua __lib__/mtdjoin.lua "MTDs"
else
    # 没有找到文件，将会提示用户如何使用
    echo "工具用途："
    echo "合并各mtd分区，生成完整的编程器固件"
    echo ""
    echo "使用方法："
    echo "1. 直接将源文件夹作为第一个参数传入"
    echo "2. 将源文件夹放到当前目录下，并重命名为MTDs"
    echo ""
    echo "支持类型："
    echo "1. 名称以z.开头的工程文件夹，由 dismantle-image 工具生成"
    echo "2. 内含全部mtd分区文件的文件夹，通常是adb提取产生的"
    echo ""
fi
