#!/bin/bash

# OpenZxicEditor
# 版权所有 (C) 2024 ufiTech & OpenZxicEditor Developers.

# 本程序是自由软件：您可以基于自由软件基金会发布的GNU Affero通用公共许可证的条款下重新分发和/或修改它，或者本许可证第三版或者（由您选择）任何后续版本。
# 分发本程序是希望它能派上用场，但没有任何担保，甚至也没有对其适销性或特定目的适用性的默示担保。更多细节请参见“GNU Affero通用公共许可证”。
# 您应该已收到本程序随附的GNU Affero通用公共许可证的副本。如未收到，请参见：http://www.gnu.org/licenses/ 。

# 获取脚本所在路径
get_script_dir() {
    local script_path="$0"
    if [ "${script_path:0:1}" != "/" ]; then
        script_path="$(command -v readlink >/dev/null 2>&1 && { readlink -f "$script_path" || :; } || { realpath "$script_path" || :; } || echo "$PWD/$script_path")"
    fi
    local script_dir="$(dirname "$script_path")"
    echo "$script_dir"
}

# 设置工作目录为所在目录
cd "$(get_script_dir)"

# 接收路径
file="$1"

# 合并所有MTD为全镜像
if [ -e "$file" ]; then
    # 使用拖拽路径
    lua __lib__/mtdjoin.lua "$file"
elif [ -d "MTDs" ]; then
    # 使用经典路径
    lua __lib__/mtdjoin.lua "MTDs"
else
    # 没有找到文件，将会提示用户如何使用
    echo "工具用途："
    echo "合并各mtd分区，生成完整的编程器固件"
    echo ""
    echo "使用方法："
    echo "1. 直接将源文件夹作为第一个参数传入"
    echo "2. 将源文件夹放到当前目录下，并重命名为MTDs"
    echo ""
    echo "支持类型："
    echo "1. 名称以z.开头的工程文件夹，由 dismantle-image 工具生成"
    echo "2. 内含全部mtd分区文件的文件夹，通常是adb提取产生的"
    echo ""
fi
