#!/bin/bash

# 获取脚本所在路径
get_script_dir() {
    local script_path="$0"
    if [ "${script_path:0:1}" != "/" ]; then
        script_path="$(command -v readlink >/dev/null 2>&1 && { readlink -f "$script_path" || :; } || { realpath "$script_path" || :; } || echo "$PWD/$script_path")"
    fi
    local script_dir="$(dirname "$script_path")"
    echo "$script_dir"
}

# 设置工作目录为所在目录
cd "$(get_script_dir)"

# 接收拖拽路径或命令行参数
#file="\$1"
file="MTDs"

# 检查文件是否存在
if [ ! -d "$file" ]; then
    echo 用途：解包工程文件夹中的所有mtd分区，必需要有json清单
    echo 用法：将工程文件夹放到当前目录下并重命名为MTDs，然后运行此程序
else
    # 解包各个分区
    lua __lib__/mtdunpk.lua
    # 重命名项目文件夹
    lua __lib__/prjmove.lua
fi
